trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "Building the project..."
      displayName: 'Build Step'
    - script: mvn clean install
      displayName: 'Maven Clean Install'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: echo "Running tests..."
      displayName: 'Test Step'
    - script: mvn test
      displayName: 'Maven Test'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo "Deploying the project..."
      displayName: 'Deploy Step'
    - script: mvn deploy
      displayName: 'Maven Deploy'

- stage: Cleanup
  jobs:
  - job: Cleanup
    steps:
    - script: echo "Cleaning up..."
      displayName: 'Cleanup Step'
    - script: mvn clean
      displayName: 'Maven Clean'